name: Quality Assurance

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.8.18
          - 3.9.19
          - 3.10.14
          - 3.11.9
          - 3.12.4
          - pypy3.8
          - pypy3.9
          - pypy3.10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run linter
        run: make lint

      - name: Run test cases
        run: make test
